version: "3.8"

services:
  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER=example
      - MYSQL_PASSWORD=example
      - MYSQL_ROOT_PASSWORD=example
      - MYSQL_DATABASE=exampleDb
    healthcheck:
      test: mysql -e "SELECT 1;"
      interval: 5s
      timeout: 4s
      retries: 10
